clone:
    hg:
        image: plugins/hg
        environment:
            - HG_SHARE_POOL=/root/.cache/hg
        volumes:
            - cache:/root/.cache

pipeline:
    tox:
        image: ${IMAGE}
        environment:
            - CFLAGS=-O0
            - DB_CACHE=/cache
            - TOX_TESTENV_PASSENV=CFLAGS DB_CACHE
            - POSTGIS_URI=postgis://postgres@postgresql:5432/
        commands:
            - echo "[repositories]" >> /root/.hgrc
            - echo "hgext.share =" >> /root/.hgrc
            - echo "[share]" >> /root/.hgrc
            - echo "pool = /root/.hgcache" >> /root/.hgrc
            - pip install tox
            - tox -e "${TOXENV}"
        volumes:
            - cache:/root/.cache

services:
    postgresql:
        image: mdillon/postgis

matrix:
    include:
        - IMAGE: python:3.5
          TOXENV: py35
        - IMAGE: python:3.6
          TOXENV: py36
        - IMAGE: python:3.7
          TOXENV: py37
