version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3"
python:
  install:
    - requirements: modules/trytond_sale_advance_payment/doc/requirements-doc.txt
sphinx:
  configuration: modules/sale_advance_payment/doc/conf.py
